import argparse

# read from command 
parser = argparse.ArgumentParser(description="Configure which setup file to use")
parser.add_argument("--setup", type=str, default="setup",
                    help="Choose which setup file to use, e.g., blast")
args = parser.parse_args()

# select files
setup_dict = {
    "setup": "setup.cpp",
    "sod": "setup_sod.cpp",
    "3Dsod": "setup_3Dsod.cpp",
    "blast": "setup_blast.cpp",
}

if args.setup not in setup_dict:
    print(f"Error: unknown setup '{args.setup}'")
    print("Available setups:", ", ".join(setup_dict.keys()))
    exit(1)

setup_file = setup_dict[args.setup]

# 写入 config.mk
with open("config.mk", "w") as f:
    f.write("# Auto-generated by configure.py\n")
    f.write(f'SETUP = {setup_file}\n')

print(f"Configuration done: ")
print(f"SETUP={setup_file}")
